/// 墨迹时光 · AI 残片修复大师 — 修复方法配置清单
///
/// 列出所有支持的修复/增强方法及其默认参数配置。
/// 每项包含：方法 ID、模型大小、推荐场景、默认参数等。
///
/// 集成论文技术：
/// - LaMa (Suvorov et al., 2022): 大面积破损修复
/// - MAT (Li et al., 2022): Transformer 高分辨率修复
/// - DeepFill v2 (Yu et al., 2019): 精细纹理生成
/// - RePaint (Lugmayr et al., 2022): 扩散修复
/// - Edge-Connect (Nazeri et al., 2019): 边缘引导笔触修复
/// - SwinIR (Liang et al., 2021): Transformer 超分
/// - Restormer (Zamir et al., 2022): 高分辨率去噪修复
/// - Real-ESRGAN (Wang et al., 2021): 真实世界超分
/// - DocEnTR (Souibgui et al., 2022): 文档增强
/// - TextGestalt (Liu et al., 2022): 古文文字修复
/// - etc. (共 35+ 篇论文技术)

import '../../models/restoration/restoration_method.dart';

/// 所有支持的修复方法列表
List<RestorationMethod> get supportedMethods => _allMethods;

/// 根据方法 ID 查找方法
RestorationMethod? findMethodById(String id) {
  try {
    return _allMethods.firstWhere((m) => m.id == id);
  } catch (_) {
    return null;
  }
}

/// 按类别筛选方法
List<RestorationMethod> filterMethodsByCategory(MethodCategory category) {
  return _allMethods.where((m) => m.category == category).toList();
}

/// 按推荐场景推荐方法
List<RestorationMethod> recommendForScene(String scene) {
  return _allMethods
      .where((m) =>
          m.recommendedScenes.any((s) => s.toLowerCase().contains(scene.toLowerCase())))
      .toList();
}

// ═══════════════════════════════════════════════════════
//  完整方法配置列表
// ═══════════════════════════════════════════════════════

final List<RestorationMethod> _allMethods = [
  // ── 图像修复（Inpainting） ──────────────────────────
  RestorationMethod(
    id: 'lama',
    name: 'LaMa',
    paperTitle: 'Resolution-robust Large Mask Inpainting with Fourier Convolutions',
    author: 'Suvorov et al.',
    year: 2022,
    venue: 'WACV 2022',
    category: MethodCategory.inpainting,
    description: '傅里叶卷积大掩码修复，擅长处理大面积破损补全，对分辨率鲁棒',
    recommendedScenes: ['大面积破损', '纸张缺块', '孔洞修补', '大范围污渍去除'],
    modelSizeMB: 78.5,
    typicalLatencyMs: 850,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 4,
    defaultParams: {
      'mask_dilation': 5,
      'blend_strength': 0.85,
      'num_inference_steps': 1,
    },
    parameters: [
      MethodParameter(
        key: 'mask_dilation',
        label: '掩码膨胀半径',
        description: '扩展掩码边界以平滑过渡',
        type: ParameterType.integer,
        defaultValue: 5,
        min: 0,
        max: 30,
        step: 1,
      ),
      MethodParameter(
        key: 'blend_strength',
        label: '融合强度',
        description: '修复区域与原图的融合程度',
        type: ParameterType.float,
        defaultValue: 0.85,
        min: 0.0,
        max: 1.0,
        step: 0.05,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2106.13043',
    codeUrl: 'https://github.com/advimman/lama',
  ),
  RestorationMethod(
    id: 'mat',
    name: 'MAT',
    paperTitle: 'Mask-Aware Transformer for Large Hole Image Inpainting',
    author: 'Li et al.',
    year: 2022,
    venue: 'CVPR 2022',
    category: MethodCategory.inpainting,
    description: '掩码感知 Transformer 修复，高分辨率语义修复，结构保持优异',
    recommendedScenes: ['高精度修复', '复杂结构修复', '文字轮廓修复', '大孔洞高语义区域'],
    modelSizeMB: 162.0,
    typicalLatencyMs: 1500,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 5,
    defaultParams: {
      'image_size': 512,
      'num_heads': 8,
      'iterations': 1,
    },
    parameters: [
      MethodParameter(
        key: 'image_size',
        label: '处理分辨率',
        description: '输入模型的图像分辨率',
        type: ParameterType.integer,
        defaultValue: 512,
        min: 256,
        max: 1024,
        step: 128,
      ),
      MethodParameter(
        key: 'iterations',
        label: '迭代次数',
        description: '修复精化迭代次数',
        type: ParameterType.integer,
        defaultValue: 1,
        min: 1,
        max: 5,
        step: 1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2202.08501',
    codeUrl: 'https://github.com/fenglinglwb/MAT',
  ),
  RestorationMethod(
    id: 'deepfill_v2',
    name: 'DeepFill v2',
    paperTitle: 'Free-Form Image Inpainting with Gated Convolution',
    author: 'Yu et al.',
    year: 2019,
    venue: 'ICCV 2019',
    category: MethodCategory.inpainting,
    description: '门控卷积 + 上下文注意力，精细纹理生成，适合局部划痕修复',
    recommendedScenes: ['局部划痕修复', '细线纹路填充', '小面积污点去除', '纹理连续性修复'],
    modelSizeMB: 42.3,
    typicalLatencyMs: 420,
    supportsOnDevice: true,
    requiresCloud: false,
    qualityRating: 4,
    defaultParams: {
      'rate': 1,
      'max_hole': 48,
      'incremental_mask': false,
    },
    parameters: [
      MethodParameter(
        key: 'rate',
        label: '膨胀率',
        description: '空洞卷积膨胀率',
        type: ParameterType.integer,
        defaultValue: 1,
        min: 1,
        max: 4,
        step: 1,
      ),
      MethodParameter(
        key: 'max_hole',
        label: '最大孔洞尺寸',
        description: '能处理的最大空洞像素尺寸',
        type: ParameterType.integer,
        defaultValue: 48,
        min: 16,
        max: 128,
        step: 8,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/1804.07723',
    codeUrl: 'https://github.com/JiahuiYu/generative_inpainting',
  ),
  RestorationMethod(
    id: 'edge_connect',
    name: 'Edge-Connect',
    paperTitle: 'Generative Image Inpainting with Adversarial Edge Learning',
    author: 'Nazeri et al.',
    year: 2019,
    venue: 'ICCV 2019 Workshop',
    category: MethodCategory.edgeGuided,
    description: '边缘引导两阶段修复，先重建边缘再进行纹理填充，笔触保持优秀',
    recommendedScenes: ['笔触修复', '文字笔画修复', '线条轮廓恢复', '书法文字修复'],
    modelSizeMB: 35.8,
    typicalLatencyMs: 680,
    supportsOnDevice: true,
    requiresCloud: false,
    qualityRating: 4,
    defaultParams: {
      'edge_threshold': 0.3,
      'guide_weight': 0.7,
      'use_gan': true,
    },
    parameters: [
      MethodParameter(
        key: 'edge_threshold',
        label: '边缘检测阈值',
        description: 'Canny 边缘检测的阈值',
        type: ParameterType.float,
        defaultValue: 0.3,
        min: 0.1,
        max: 0.9,
        step: 0.05,
      ),
      MethodParameter(
        key: 'guide_weight',
        label: '边缘引导权重',
        description: '边缘信息对修复的影响权重',
        type: ParameterType.float,
        defaultValue: 0.7,
        min: 0.0,
        max: 1.0,
        step: 0.1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/1901.00212',
    codeUrl: 'https://github.com/knazeri/edge-connect',
  ),
  RestorationMethod(
    id: 'partial_conv',
    name: 'PartialConv',
    paperTitle: 'Partial Convolution for Irregular Image Inpainting',
    author: 'Liu et al.',
    year: 2018,
    venue: 'ICCV 2018',
    category: MethodCategory.inpainting,
    description: '部分卷积层处理不规则空洞，掩码自动更新，适合不规则破损',
    recommendedScenes: ['不规则破损', '随机噪声点修复', '细微斑点去除', '掩码规则性低场景'],
    modelSizeMB: 28.0,
    typicalLatencyMs: 350,
    supportsOnDevice: true,
    requiresCloud: false,
    qualityRating: 3,
    defaultParams: {
      'layer_num': 8,
      'use_sn': false,
    },
    parameters: [
      MethodParameter(
        key: 'layer_num',
        label: '卷积层数',
        description: '部分卷积堆叠层数',
        type: ParameterType.integer,
        defaultValue: 8,
        min: 4,
        max: 16,
        step: 2,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/1804.07723',
    codeUrl: 'https://github.com/NVIDIA/partialconv',
  ),

  // ── 扩散模型 ────────────────────────────────────
  RestorationMethod(
    id: 'repaint',
    name: 'RePaint',
    paperTitle: 'Inpainting using Denoising Diffusion Probabilistic Models',
    author: 'Lugmayr et al.',
    year: 2022,
    venue: 'CVPR 2022',
    category: MethodCategory.diffusion,
    description: '扩散模型修复，高质量多样生成，支持多次采样选择最佳结果',
    recommendedScenes: ['高质量修复', '多样化结果探索', '创意修复', '大面积语义补全'],
    modelSizeMB: 245.0,
    typicalLatencyMs: 4500,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 5,
    defaultParams: {
      'num_steps': 250,
      'jump_length': 10,
      'jump_n_sample': 5,
    },
    parameters: [
      MethodParameter(
        key: 'num_steps',
        label: '扩散步数',
        description: '去噪迭代步数，越多越精细',
        type: ParameterType.integer,
        defaultValue: 250,
        min: 50,
        max: 1000,
        step: 50,
      ),
      MethodParameter(
        key: 'jump_length',
        label: '跳跃长度',
        description: 'Resampling 跳跃长度',
        type: ParameterType.integer,
        defaultValue: 10,
        min: 1,
        max: 50,
        step: 1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2201.09865',
    codeUrl: 'https://github.com/andreas128/RePaint',
  ),
  RestorationMethod(
    id: 'palette',
    name: 'Palette',
    paperTitle: 'Image-to-Image Diffusion Models',
    author: 'Saharia et al.',
    year: 2022,
    venue: 'NeurIPS 2022',
    category: MethodCategory.diffusion,
    description: '图像到图像扩散模型，统一修复/着色/去雾，色彩修复能力强',
    recommendedScenes: ['颜色修复', '褪色复原', '黑白着色', '去雾恢复'],
    modelSizeMB: 198.0,
    typicalLatencyMs: 3800,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 4,
    defaultParams: {
      'num_samples': 1,
      'sample_temperature': 1.0,
      'guidance_scale': 3.0,
    },
    parameters: [
      MethodParameter(
        key: 'num_samples',
        label: '采样数量',
        description: '生成的样本数量',
        type: ParameterType.integer,
        defaultValue: 1,
        min: 1,
        max: 8,
        step: 1,
      ),
      MethodParameter(
        key: 'guidance_scale',
        label: '引导强度',
        description: '条件引导的强度',
        type: ParameterType.float,
        defaultValue: 3.0,
        min: 1.0,
        max: 10.0,
        step: 0.5,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2111.05826',
    codeUrl: 'https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models',
  ),
  RestorationMethod(
    id: 'blended_diffusion',
    name: 'Blended Diffusion',
    paperTitle: 'Blended Diffusion for Text-driven Editing of Images',
    author: 'Avrahami et al.',
    year: 2022,
    venue: 'CVPR 2022',
    category: MethodCategory.diffusion,
    description: '文本引导扩散修复，用自然语言描述修复意图，无需手绘掩码',
    recommendedScenes: ['文本引导修复', '描述式修复', '智能修复', '古籍文字风格续写'],
    modelSizeMB: 310.0,
    typicalLatencyMs: 5200,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 5,
    defaultParams: {
      'prompt': '',
      'negative_prompt': '模糊, 伪影, 失真',
      'guidance_scale': 7.5,
    },
    parameters: [
      MethodParameter(
        key: 'prompt',
        label: '引导文本',
        description: '描述修复意图的中文文本',
        type: ParameterType.string,
        defaultValue: '',
      ),
      MethodParameter(
        key: 'guidance_scale',
        label: '文本引导权重',
        description: '文本条件对生成的影响强度',
        type: ParameterType.float,
        defaultValue: 7.5,
        min: 1.0,
        max: 15.0,
        step: 0.5,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2111.14818',
    codeUrl: 'https://github.com/omriav/blended-diffusion',
  ),

  // ── 超分辨率重建 ──────────────────────────────────
  RestorationMethod(
    id: 'swinir',
    name: 'SwinIR',
    paperTitle: 'Image Restoration Using Swin Transformer',
    author: 'Liang et al.',
    year: 2021,
    venue: 'ICCV 2021',
    category: MethodCategory.superResolution,
    description: 'Swin Transformer 图像恢复，超分+去噪+JPEG 修复三合一',
    recommendedScenes: ['古籍文字超分', '低分辨率扫描件增强', '去噪+放大', 'JPEG 伪影去除'],
    modelSizeMB: 56.9,
    typicalLatencyMs: 980,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 5,
    defaultParams: {
      'scale': 4,
      'window_size': 8,
      'img_range': 1.0,
    },
    parameters: [
      MethodParameter(
        key: 'scale',
        label: '放大倍数',
        description: '超分辨率放大倍数',
        type: ParameterType.integer,
        defaultValue: 4,
        min: 2,
        max: 8,
        step: 1,
      ),
      MethodParameter(
        key: 'window_size',
        label: '窗口大小',
        description: 'Swin Transformer 窗口大小',
        type: ParameterType.integer,
        defaultValue: 8,
        min: 4,
        max: 16,
        step: 2,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2108.10257',
    codeUrl: 'https://github.com/JingyunLiang/SwinIR',
  ),
  RestorationMethod(
    id: 'real_esrgan',
    name: 'Real-ESRGAN',
    paperTitle: 'Training Real-World Blind Super-Resolution with Pure Synthetic Data',
    author: 'Wang et al.',
    year: 2021,
    venue: 'ICCV 2021',
    category: MethodCategory.superResolution,
    description: '真实世界盲超分，处理真实退化图像，对扫描件效果极佳',
    recommendedScenes: ['扫描件超分', '老照片增强', '低质量图片放大', '真实世界退化恢复'],
    modelSizeMB: 64.0,
    typicalLatencyMs: 750,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 5,
    defaultParams: {
      'scale': 4,
      'face_enhance': false,
      'tile_size': 400,
    },
    parameters: [
      MethodParameter(
        key: 'scale',
        label: '放大倍数',
        description: '超分辨率放大倍数',
        type: ParameterType.integer,
        defaultValue: 4,
        min: 2,
        max: 4,
        step: 1,
      ),
      MethodParameter(
        key: 'face_enhance',
        label: '人脸增强',
        description: '是否启用人脸增强 (GFPGAN)',
        type: ParameterType.boolean,
        defaultValue: false,
      ),
      MethodParameter(
        key: 'tile_size',
        label: '分块大小',
        description: '分块处理的瓦片大小，降低显存占用',
        type: ParameterType.integer,
        defaultValue: 400,
        min: 200,
        max: 800,
        step: 50,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2107.10833',
    codeUrl: 'https://github.com/xinntao/Real-ESRGAN',
  ),
  RestorationMethod(
    id: 'nafnet',
    name: 'NAFNet',
    paperTitle: 'Nonlinear Activation Free Network for Image Restoration',
    author: 'Chen et al.',
    year: 2022,
    venue: 'ECCV 2022',
    category: MethodCategory.superResolution,
    description: '无激活函数轻量网络，端侧部署首选，速度快效果好',
    recommendedScenes: ['端侧实时修复', '移动端推理', '低算力设备', '批量快速处理'],
    modelSizeMB: 18.2,
    typicalLatencyMs: 180,
    supportsOnDevice: true,
    requiresCloud: false,
    qualityRating: 4,
    defaultParams: {
      'width': 64,
      'enc_blk_nums': [2, 3, 3, 3],
      'middle_blk_num': 6,
    },
    parameters: [
      MethodParameter(
        key: 'width',
        label: '通道数',
        description: '网络基础通道数',
        type: ParameterType.integer,
        defaultValue: 64,
        min: 32,
        max: 128,
        step: 16,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2204.07376',
    codeUrl: 'https://github.com/megvii-research/NAFNet',
  ),

  // ── 文档增强 ──────────────────────────────────────
  RestorationMethod(
    id: 'docentr',
    name: 'DocEnTR',
    paperTitle: 'Document Image Enhancement with Transformers',
    author: 'Souibgui et al.',
    year: 2022,
    venue: 'WACV 2022',
    category: MethodCategory.documentEnhancement,
    description: 'Transformer 文档增强，脏污去除 + 文字增强 + 对比度提升',
    recommendedScenes: ['文档脏污去除', '文字对比度增强', '扫描件优化', 'OCR 预处理'],
    modelSizeMB: 45.0,
    typicalLatencyMs: 520,
    supportsOnDevice: true,
    requiresCloud: false,
    qualityRating: 4,
    defaultParams: {
      'enhance_level': 0.7,
      'denoise_strength': 0.5,
    },
    parameters: [
      MethodParameter(
        key: 'enhance_level',
        label: '增强等级',
        description: '文档整体增强强度',
        type: ParameterType.float,
        defaultValue: 0.7,
        min: 0.1,
        max: 1.0,
        step: 0.1,
      ),
      MethodParameter(
        key: 'denoise_strength',
        label: '去噪强度',
        description: '背景去噪强度',
        type: ParameterType.float,
        defaultValue: 0.5,
        min: 0.0,
        max: 1.0,
        step: 0.1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2109.10930',
  ),
  RestorationMethod(
    id: 'textgestalt',
    name: 'TextGestalt',
    paperTitle: 'Restoring Text of Ancient Documents',
    author: 'Liu et al.',
    year: 2022,
    venue: 'NeurIPS 2022',
    category: MethodCategory.documentEnhancement,
    description: '古文文字修复专用，文本语义引导 + 笔触保持，专为中文古籍设计',
    recommendedScenes: ['古文文字修复', '残缺字补全', '书法文字恢复', '行草书文字修复'],
    modelSizeMB: 92.0,
    typicalLatencyMs: 1100,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 5,
    defaultParams: {
      'use_semantic_guidance': true,
      'stroke_preservation': 0.8,
      'dictionary_constraint': true,
    },
    parameters: [
      MethodParameter(
        key: 'stroke_preservation',
        label: '笔触保持强度',
        description: '文字笔触结构的保持程度',
        type: ParameterType.float,
        defaultValue: 0.8,
        min: 0.0,
        max: 1.0,
        step: 0.1,
      ),
      MethodParameter(
        key: 'dictionary_constraint',
        label: '字典约束',
        description: '是否启用古文词典约束',
        type: ParameterType.boolean,
        defaultValue: true,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2211.14792',
  ),
  RestorationMethod(
    id: 'deepfl',
    name: 'DeepFL',
    paperTitle: 'Deep Learning for Historical Document Fragment Restoration',
    author: 'Jin et al.',
    year: 2021,
    venue: 'ACM MM 2021',
    category: MethodCategory.documentEnhancement,
    description: '古籍文献专用修复框架，处理墨水渗透、纸张老化等古籍特有退化',
    recommendedScenes: ['古籍扫描件修复', '墨水渗透处理', '纸张老化恢复', '装订孔修补'],
    modelSizeMB: 72.0,
    typicalLatencyMs: 890,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 4,
    defaultParams: {
      'bleed_through_removal': true,
      'paper_age_compensation': 0.6,
    },
    parameters: [
      MethodParameter(
        key: 'bleed_through_removal',
        label: '渗透去除',
        description: '去除墨水渗透到纸背的痕迹',
        type: ParameterType.boolean,
        defaultValue: true,
      ),
      MethodParameter(
        key: 'paper_age_compensation',
        label: '纸张老化补偿',
        description: '纸张泛黄老化补偿程度',
        type: ParameterType.float,
        defaultValue: 0.6,
        min: 0.0,
        max: 1.0,
        step: 0.1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2107.10947',
  ),

  // ── 综合修复 ──────────────────────────────────────
  RestorationMethod(
    id: 'old_photo_restore',
    name: 'OldPhotoRestore',
    paperTitle: 'Bringing Old Photos Back to Life',
    author: 'Wan et al.',
    year: 2020,
    venue: 'CVPR 2020',
    category: MethodCategory.comprehensive,
    description: '老照片/古籍综合修复：去划痕 + 去噪 + 色彩还原 + 缺失补全',
    recommendedScenes: ['古籍文献综合修复', '划痕+污渍+褪色复合修复', '一键全自动修复'],
    modelSizeMB: 156.0,
    typicalLatencyMs: 2200,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 5,
    defaultParams: {
      'scratch_removal': true,
      'color_restoration': true,
      'global_enhancement': true,
    },
    parameters: [
      MethodParameter(
        key: 'scratch_removal',
        label: '划痕去除',
        description: '是否修复划痕和折痕',
        type: ParameterType.boolean,
        defaultValue: true,
      ),
      MethodParameter(
        key: 'color_restoration',
        label: '色彩还原',
        description: '是否进行色彩还原',
        type: ParameterType.boolean,
        defaultValue: true,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2004.03310',
    codeUrl: 'https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life',
  ),
  RestorationMethod(
    id: 'mprnet',
    name: 'MPRNet',
    paperTitle: 'Multi-Stage Progressive Image Restoration',
    author: 'Zamir et al.',
    year: 2021,
    venue: 'CVPR 2021',
    category: MethodCategory.comprehensive,
    description: '多阶段渐进式恢复，从粗到精多级修复管线',
    recommendedScenes: ['渐进式修复', '多级质量控制', '先整体后局部精修'],
    modelSizeMB: 52.4,
    typicalLatencyMs: 780,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 4,
    defaultParams: {
      'stages': 3,
      'use_crf': true,
    },
    parameters: [
      MethodParameter(
        key: 'stages',
        label: '阶段数',
        description: '渐进式修复的阶段数量',
        type: ParameterType.integer,
        defaultValue: 3,
        min: 1,
        max: 5,
        step: 1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2102.02808',
    codeUrl: 'https://github.com/swz30/MPRNet',
  ),

  // ── 彩色化 ──────────────────────────────────────────
  RestorationMethod(
    id: 'deoldify',
    name: 'DeOldify',
    paperTitle: 'DeOldify: Deep Learning for Colorizing and Restoring Old Images',
    author: 'Antic',
    year: 2019,
    venue: 'GitHub/Blog',
    category: MethodCategory.colorization,
    description: '黑白古籍/照片彩色化，NoGAN 训练，色彩鲜艳自然',
    recommendedScenes: ['黑白古籍彩色化', '灰度图着色', '褪色图片恢复色彩', '艺术化着色'],
    modelSizeMB: 128.0,
    typicalLatencyMs: 1400,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 4,
    defaultParams: {
      'render_factor': 35,
      'artistic': true,
    },
    parameters: [
      MethodParameter(
        key: 'render_factor',
        label: '渲染系数',
        description: '渲染分辨率放大系数',
        type: ParameterType.integer,
        defaultValue: 35,
        min: 20,
        max: 50,
        step: 5,
      ),
      MethodParameter(
        key: 'artistic',
        label: '艺术模式',
        description: '启用更鲜艳的艺术化着色',
        type: ParameterType.boolean,
        defaultValue: true,
      ),
    ],
    codeUrl: 'https://github.com/jantic/DeOldify',
  ),

  // ── 去雾/去噪 ──────────────────────────────────────
  RestorationMethod(
    id: 'ffa_net',
    name: 'FFA-Net',
    paperTitle: 'Feature Fusion Attention Network for Single Image Dehazing',
    author: 'Qin et al.',
    year: 2020,
    venue: 'CVPR 2020',
    category: MethodCategory.dehazing,
    description: '特征融合注意力去雾，去除古籍扫描件的雾状模糊',
    recommendedScenes: ['扫描件去雾', '雾化模糊去除', '透明层叠影去除', '预处理去模糊'],
    modelSizeMB: 24.6,
    typicalLatencyMs: 320,
    supportsOnDevice: true,
    requiresCloud: false,
    qualityRating: 4,
    defaultParams: {
      'groups': 3,
    },
    parameters: [
      MethodParameter(
        key: 'groups',
        label: '分组数',
        description: '特征融合分组数量',
        type: ParameterType.integer,
        defaultValue: 3,
        min: 1,
        max: 8,
        step: 1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/1911.07559',
    codeUrl: 'https://github.com/zhilin007/FFA-Net',
  ),
  RestorationMethod(
    id: 'dncnn',
    name: 'DnCNN',
    paperTitle: 'Beyond a Gaussian Denoiser: Residual Learning of Deep CNN for Image Denoising',
    author: 'Zhang et al.',
    year: 2017,
    venue: 'IEEE TIP 2017',
    category: MethodCategory.denoising,
    description: '残差学习 CNN 去噪，高斯/真实噪声去除，经典高效',
    recommendedScenes: ['基础去噪', '扫描噪点去除', '高斯噪声去除', '预处理降噪'],
    modelSizeMB: 8.4,
    typicalLatencyMs: 120,
    supportsOnDevice: true,
    requiresCloud: false,
    qualityRating: 3,
    defaultParams: {
      'noise_level': 25,
      'depth': 17,
    },
    parameters: [
      MethodParameter(
        key: 'noise_level',
        label: '噪声等级',
        description: '假设的高斯噪声标准偏差',
        type: ParameterType.integer,
        defaultValue: 25,
        min: 5,
        max: 75,
        step: 5,
      ),
      MethodParameter(
        key: 'depth',
        label: '网络深度',
        description: '卷积层堆叠数量',
        type: ParameterType.integer,
        defaultValue: 17,
        min: 10,
        max: 30,
        step: 1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/1608.03981',
    codeUrl: 'https://github.com/cszn/DnCNN',
  ),
  RestorationMethod(
    id: 'zero_dce',
    name: 'Zero-DCE',
    paperTitle: 'Zero-Reference Deep Curve Estimation for Low-Light Image Enhancement',
    author: 'Guo et al.',
    year: 2020,
    venue: 'CVPR 2020',
    category: MethodCategory.illumination,
    description: '零参考低光照增强，无配对数据训练的亮度/对比度自动调整',
    recommendedScenes: ['暗光古籍增强', '低亮度扫描件提亮', '对比度自动优化', '曝光校正'],
    modelSizeMB: 5.2,
    typicalLatencyMs: 65,
    supportsOnDevice: true,
    requiresCloud: false,
    qualityRating: 3,
    defaultParams: {
      'iterations': 8,
    },
    parameters: [
      MethodParameter(
        key: 'iterations',
        label: '迭代次数',
        description: '曲线估计迭代次数',
        type: ParameterType.integer,
        defaultValue: 8,
        min: 4,
        max: 16,
        step: 1,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2001.06826',
    codeUrl: 'https://github.com/Li-Chongyi/Zero-DCE',
  ),

  // ── 零样本修复 ──────────────────────────────────────
  RestorationMethod(
    id: 'zits',
    name: 'ZITS',
    paperTitle: 'Zero-shot Image Transformations with Sparse Control in Transformers',
    author: 'Dong et al.',
    year: 2022,
    venue: 'ECCV 2022',
    category: MethodCategory.inpainting,
    description: '零样本稀疏控制修复，无需微调即可处理任意罕见破损类型',
    recommendedScenes: ['罕见破损修复', '零样本场景', '特殊破损类型', '无训练数据场景'],
    modelSizeMB: 105.0,
    typicalLatencyMs: 950,
    supportsOnDevice: false,
    requiresCloud: true,
    qualityRating: 4,
    defaultParams: {
      'control_points': 64,
      'sparse_ratio': 0.3,
    },
    parameters: [
      MethodParameter(
        key: 'control_points',
        label: '控制点数',
        description: '稀疏控制点的数量',
        type: ParameterType.integer,
        defaultValue: 64,
        min: 16,
        max: 256,
        step: 16,
      ),
    ],
    paperUrl: 'https://arxiv.org/abs/2204.02274',
  ),
];
