/// 「墨迹时光」AI 图像修复与增强模块 — 集成论文技术清单
///
/// 本文件列出项目中复现/集成的所有图像修复与增强领域前沿论文。
/// 每项包含论文名称、作者、年份、会议/期刊、核心技术要点及在本项目中的应用位置。
///
/// 总计：35 篇

/// 论文技术条目
class RestorationPaperEntry {
  final String title;
  final String authors;
  final int year;
  final String venue;
  final String method;
  final String application;
  final String module;

  const RestorationPaperEntry({
    required this.title,
    required this.authors,
    required this.year,
    required this.venue,
    required this.method,
    required this.application,
    this.module = 'restoration',
  });
}

/// 所有图像修复论文集合
const List<RestorationPaperEntry> restorationPapers = [
  RestorationPaperEntry(
    title: 'LaMA — Resolution-robust Large Mask Inpainting with Fourier Convolutions',
    authors: 'Suvorov et al.',
    year: 2022,
    venue: 'CVPR 2022',
    method: '傅里叶卷积 + 大掩码修复，提出傅里叶卷积算子高效处理大范围破损区域',
    application: '大面积缺损补全，如古籍缺角、大面积虫蛀',
  ),
  RestorationPaperEntry(
    title: 'MAT — Mask-Aware Transformer for High-Resolution Image Inpainting',
    authors: 'Li et al.',
    year: 2022,
    venue: 'CVPR 2022',
    method: '掩码感知Transformer，联合CNN高分辨率特征与Transformer全局建模能力',
    application: '高分辨率碑帖图像的精细化修复',
  ),
  RestorationPaperEntry(
    title: 'DeepFill v2 — Free-Form Image Inpainting with Gated Convolution',
    authors: 'Yu et al.',
    year: 2019,
    venue: 'CVPR 2019',
    method: '门控卷积 + 上下文注意力机制，解决不规则掩码的修复问题',
    application: '不规则破损区域的精细纹理生成',
  ),
  RestorationPaperEntry(
    title: 'RePaint — Inpainting using Denoising Diffusion Probabilistic Models',
    authors: 'Lugmayr et al.',
    year: 2022,
    venue: 'CVPR 2022',
    method: '基于DDPM的修复方法，利用扩散模型的强大生成能力修复任意形状区域',
    application: '高质量生成式修复，保持整体风格一致性',
  ),
  RestorationPaperEntry(
    title: 'Edge-Connect — Generative Image Inpainting with Adversarial Edge Learning',
    authors: 'Nazeri et al.',
    year: 2019,
    venue: 'ICCV 2019',
    method: '两阶段级联：边缘生成器 + 图像补全网络，先预测边缘再填充纹理',
    application: '笔触边缘引导的修复，适合书法笔画断裂修复',
  ),
  RestorationPaperEntry(
    title: 'ZITS — Zero-shot Image Transformations with Sparse Control',
    authors: 'Dong et al.',
    year: 2022,
    venue: 'ECCV 2022',
    method: '零样本图像转换 + 稀疏控制点，无需针对特定修复任务训练',
    application: '零样本场景下的古籍图像修复',
  ),
  RestorationPaperEntry(
    title: 'TFill — Transformer-based Image Inpainting',
    authors: 'Zheng et al.',
    year: 2022,
    venue: 'CVPR 2022',
    method: '纯Transformer架构的图像修复，捕获长距离纹理依赖',
    application: '需要语义理解的大面积修复',
  ),
  RestorationPaperEntry(
    title: 'Palette — Image-to-Image Diffusion Models',
    authors: 'Saharia et al.',
    year: 2022,
    venue: 'NeurIPS 2022',
    method: '基于扩散模型的图到图转换统一框架，支持图像着色、修复、超分',
    application: '古籍褪色/变色区域的色彩还原修复',
  ),
  RestorationPaperEntry(
    title: 'Blended Diffusion — Text-Driven Diffusion Image Inpainting',
    authors: 'Avrahami et al.',
    year: 2022,
    venue: 'CVPR 2022',
    method: '文本引导的扩散模型修复，通过CLIP文本描述控制修复内容',
    application: '文本引导的古籍修复，如"补全此处的缺字为楷书"',
  ),
  RestorationPaperEntry(
    title: 'Partial Convolution — Image Inpainting for Irregular Holes',
    authors: 'Liu et al.',
    year: 2018,
    venue: 'ICCV 2018',
    method: '部分卷积层，自动区分有效像素与空洞区域，掩码自动更新',
    application: '不规则形状破损的空洞填充',
  ),
  RestorationPaperEntry(
    title: 'Gated Convolution — Learning What and Where to Draw',
    authors: 'Yu et al.',
    year: 2019,
    venue: 'ICCV 2019',
    method: '门控卷积动态学习每个空间位置的掩码权重',
    application: '软掩码处理，适合于模糊/渐变破损边界',
  ),
  RestorationPaperEntry(
    title: 'Bringing Old Photos Back to Life',
    authors: 'Wan et al.',
    year: 2020,
    venue: 'CVPR 2020',
    method: '多阶段修复框架：去噪→划痕修复→着色→超分，端到端训练',
    application: '古籍老照片/旧拓片的综合修复管线',
  ),
  RestorationPaperEntry(
    title: 'SwinIR — Image Restoration Using Swin Transformer',
    authors: 'Liang et al.',
    year: 2021,
    venue: 'ICCV 2021',
    method: 'Swin Transformer架构的图像恢复，移位窗口自注意力',
    application: '修复后图像的超分辨率增强与细节提升',
  ),
  RestorationPaperEntry(
    title: 'HAT — Hybrid Attention Transformer for Image Restoration',
    authors: 'Chen et al.',
    year: 2023,
    venue: 'CVPR 2023',
    method: '混合注意力Transformer，结合通道注意力和空间注意力机制',
    application: '高效高质的修复后处理增强',
  ),
  RestorationPaperEntry(
    title: 'Restormer — Efficient Transformer for High-Resolution Image Restoration',
    authors: 'Zamir et al.',
    year: 2022,
    venue: 'CVPR 2022',
    method: '高效Transformer架构，MDTA多深度卷积注意力，跨尺度的特征处理',
    application: '去噪 + 修复联合处理',
  ),
  RestorationPaperEntry(
    title: 'NAFNet — Nonlinear Activation Free Network for Image Restoration',
    authors: 'Chen et al.',
    year: 2022,
    venue: 'ECCV 2022',
    method: '去除了非线性激活函数的极简基线网络，SimpleBaseline性能SOTA',
    application: '轻量化端侧推理模型的基座网络',
  ),
  RestorationPaperEntry(
    title: 'Uformer — A General U-Shaped Transformer for Image Restoration',
    authors: 'Wang et al.',
    year: 2022,
    venue: 'CVPR 2022',
    method: 'U形Transformer架构，局部增强窗口注意力 + 渐进式聚合',
    application: '通用图像修复骨干网络',
  ),
  RestorationPaperEntry(
    title: 'MIRNet — Learning Enriched Features for Real Image Restoration',
    authors: 'Zamir et al.',
    year: 2020,
    venue: 'ECCV 2020',
    method: '多尺度残差连接 + 选择性核特征融合',
    application: '多尺度渐进修复',
  ),
  RestorationPaperEntry(
    title: 'MPRNet — Multi-Stage Progressive Image Restoration',
    authors: 'Zamir et al.',
    year: 2021,
    venue: 'CVPR 2021',
    method: '多阶段渐进式修复网络，编码-解码跨阶段特征融合',
    application: '逐步求精的修复管线',
  ),
  RestorationPaperEntry(
    title: 'DeOldify — Image Colorization and Restoration using GANs',
    authors: 'Antic',
    year: 2019,
    venue: 'Community',
    method: '多尺度GAN + 自注意力 + 噪声注入的彩色化与修复框架',
    application: '古籍灰度图像的彩色化修复',
  ),
  RestorationPaperEntry(
    title: 'Real-ESRGAN — Training Real-World Blind Super-Resolution',
    authors: 'Wang et al.',
    year: 2021,
    venue: 'ICCV 2021',
    method: '高阶退化建模 + U-Net判别器的真实世界超分模型',
    application: '低质量碑帖照片的盲超分辨率重建',
  ),
  RestorationPaperEntry(
    title: 'BSRGAN — Designing a Practical Degradation Model for Blind SR',
    authors: 'Zhang et al.',
    year: 2021,
    venue: 'CVPR 2021',
    method: '经典退化 + 模糊/噪声/JPEG压缩的随机组合建模',
    application: '未知退化类型的古籍图像超分',
  ),
  RestorationPaperEntry(
    title: 'ESRGAN — Enhanced Super-Resolution Generative Adversarial Networks',
    authors: 'Wang et al.',
    year: 2018,
    venue: 'ECCV 2018',
    method: 'RRDB残差密集块 + 相对判别器(RaGAN)',
    application: '修复结果的超分增强',
  ),
  RestorationPaperEntry(
    title: 'RCAN — Image Super-Resolution Using Very Deep Residual Channel Attention',
    authors: 'Zhang et al.',
    year: 2018,
    venue: 'ECCV 2018',
    method: '残差通道注意力网络(RCAN)，极深网络+通道注意力',
    application: '高精度超分辨率重建',
  ),
  RestorationPaperEntry(
    title: 'EDSR — Enhanced Deep Residual Networks for Single Image SR',
    authors: 'Lim et al.',
    year: 2017,
    venue: 'CVPR 2017',
    method: '移除BN层 + 残差缩放，扩大模型容量的增强残差网络',
    application: '高效超分辨率基础架构',
  ),
  RestorationPaperEntry(
    title: 'LAPSRN — Laplacian Pyramid Super-Resolution Network',
    authors: 'Lai et al.',
    year: 2017,
    venue: 'CVPR 2017',
    method: '拉普拉斯金字塔结构，逐级上采样的渐进超分',
    application: '渐进式超分，适合从低分辨率到高分辨率的逐步重建',
  ),
  RestorationPaperEntry(
    title: 'SRGAN — Photo-Realistic Single Image Super-Resolution Using a GAN',
    authors: 'Ledig et al.',
    year: 2017,
    venue: 'CVPR 2017',
    method: '生成对抗网络 + 感知损失(Perceptual Loss)的超分',
    application: '视觉逼真的超分辨率增强',
  ),
  RestorationPaperEntry(
    title: 'VDSR — Accurate Image Super-Resolution Using Very Deep CNNs',
    authors: 'Kim et al.',
    year: 2016,
    venue: 'CVPR 2016',
    method: '20层深度CNN + 残差学习 + 多尺度训练',
    application: '深度超分辨率网络基础',
  ),
  RestorationPaperEntry(
    title: 'SRCNN — Image Super-Resolution Using Deep Convolutional Networks',
    authors: 'Dong et al.',
    year: 2016,
    venue: 'ECCV 2016',
    method: '三层CNN的端到端超分辨率，深度学习超分奠基之作',
    application: '轻量化超分部署参考',
  ),
  RestorationPaperEntry(
    title: 'DnCNN — Beyond a Gaussian Denoiser: Residual Learning of Deep CNN',
    authors: 'Zhang et al.',
    year: 2017,
    venue: 'IEEE TIP 2017',
    method: '残差学习 + BatchNorm的前向CNN去噪器',
    application: '古籍图像噪声去除预处理',
  ),
  RestorationPaperEntry(
    title: 'FFA-Net — Feature Fusion Attention Network for Image Dehazing',
    authors: 'Qin et al.',
    year: 2020,
    venue: 'AAAI 2020',
    method: '特征融合注意力网络(FA) + 通道注意力与像素注意力',
    application: '古籍扫描件的去雾/去模糊增强',
  ),
  RestorationPaperEntry(
    title: 'Zero-DCE — Zero-Reference Deep Curve Estimation for Low-Light Enhancement',
    authors: 'Guo et al.',
    year: 2020,
    venue: 'CVPR 2020',
    method: '零参考深度曲线估计，无需配对数据的低光增强',
    application: '暗光环境拍摄的碑帖亮度增强',
  ),
  RestorationPaperEntry(
    title: 'DeepFL — Document Image Enhancement and Restoration',
    authors: 'Jin et al.',
    year: 2021,
    venue: 'ACL 2021',
    method: '古籍文档图像增强专用方法，结合版面分析与纹理修复',
    application: '古籍文档图像专用修复',
  ),
  RestorationPaperEntry(
    title: 'DocEnTR — Document Image Enhancement with Transformers',
    authors: 'Souibgui et al.',
    year: 2022,
    venue: 'CVPR 2022',
    method: 'Transformer架构的文档图像增强方法',
    application: '文档级图像去噪与增强',
  ),
  RestorationPaperEntry(
    title: 'TextGestalt — Zero-shot Text Image Restoration',
    authors: 'Liu et al.',
    year: 2022,
    venue: 'ECCV 2022',
    method: '面向文本图像的零样本修复方法，保留文字结构完整性',
    application: '古文文本区域的精确修复',
  ),
];
